{% set name = "gssapi" %}
{% set version = "1.9.0" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f468fac8f3f5fca8f4d1ca19e3cd4d2e10bd91074e7285464b22715d13548afe
  patches:                  # [win or osx]
    - 0001-fix-setup.patch  # [osx]
    - fix_path.patch        # [win]

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv  # [not win]
  script_env:
    - GSSAPI_SUPPORT_DETECT=false  # [build_platform != target_platform]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - patch        # [unix]
    - msys2-patch  # [win]
  host:
    - python
    - cython >=0.29.29,<4.0.0a0
    - libkrb5 {{ krb5 }}
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - decorator

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_family: Other
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  description: |
    Python-GSSAPI provides both low-level and high level wrappers around the GSSAPI C libraries.
    While it focuses on the Kerberos mechanism, it should also be useable with other GSSAPI mechanisms.
  doc_url: https://pythongssapi.github.io/python-gssapi/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
