{% set name = "gssapi" %}
{% set version = "1.8.3" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa3c8d0b1526f52559552bb2c9d2d6be013d76a8e5db00b39a1db5727e93b0b0
  patches:
    - 0001-fix-setup.patch  # [osx]
    - fix_path.patch       # [win]
    - use-distutils-from-stdlib.patch

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  script_env:
    - GSSAPI_SUPPORT_DETECT=false  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - cython >=0.29.29,<4.0.0a0
    - krb5 1.20
    - pip
    - setuptools
    - wheel
  run:
    - python
    - decorator

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_family: Other
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  description: |
    Python-GSSAPI provides both low-level and high level wrappers around the GSSAPI C libraries.
    While it focuses on the Kerberos mechanism, it should also be useable with other GSSAPI mechanisms.
  doc_url: https://pythongssapi.github.io/python-gssapi/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
