{% set name = "gssapi" %}
{% set version = "1.8.3" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa3c8d0b1526f52559552bb2c9d2d6be013d76a8e5db00b39a1db5727e93b0b0
  patches:                  # [win or osx]
    - 0001-fix-setup.patch  # [osx]
    - fix_path.patch        # [win]

build:
  number: 2
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv  # [not win]
  script_env:
    - GSSAPI_SUPPORT_DETECT=false  # [build_platform != target_platform]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - patch        # [unix]
    - msys2-patch  # [win]
  host:
    - python
    - cython >=0.29.29,<4.0.0a0
    # libkrb5 1.21.3 (libraries and headers) fails on Windows with an error: "C2065: 'gss_key_value_set_desc': undeclared identifier"
    # but krb5 (plus executables) works fine.
    - krb5 {{ krb5 }}     # [win]
    - libkrb5 {{ krb5 }}  # [unix]
    - pip
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - decorator
    # libkrb5 provides gssapi64.dll on Windows
    - libkrb5  # [win]

# The tests fail because of the error "FileNotFoundError: [Errno 2] No such file or directory: '/usr/sbin/kdb5_util'".
# The real location of kdb5_util is $PREFIX/sbin not /usr/sbin but it's hardcoded in the k5test's source code,
# see https://github.com/pythongssapi/k5test/blob/17512bd2137ffcdd1fdb7ff4210891ad34d27803/k5test/realm.py#L459
{% set tests_to_skip = "_not_a_real_test" %}
{% set tests_to_skip = tests_to_skip + " or CredsTestCase or MechsTestCase or NamesTestCase or SecurityContextTestCase or TestBaseUtilities" %}
{% set tests_to_skip = tests_to_skip + " or test_basic_init_default_ctx or test_bad_channel_binding_raises_error or test_basic_accept_context or test_basic_accept_context_no_acceptor_creds or test_channel_bindings" %}
{% set tests_to_skip = tests_to_skip + " or TestWrapUnwrap" %}

{% set tests_to_ignore = "" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=%SP_DIR%\\gssapi\\tests\\test_high_level.py --ignore=%SP_DIR%\\gssapi\\tests\\test_raw.py" %}  # [win]

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions
  requires:
    - pip
    - pytest
    - parameterized
  commands:
    - pip check
    - python -c "import importlib.metadata; assert importlib.metadata.version('gssapi') == '{{ version }}'"
    - pip install k5test
    - pytest -v ${SP_DIR}/gssapi/tests -k "not ({{ tests_to_skip }})"                        # [unix]
    # subprocess.CalledProcessError: Command 'krb5-config --prefix' returned non-zero exit status 1 on Windows.
    - pytest --pyargs %SP_DIR%\gssapi\tests {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_family: Other
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  description: |
    Python-GSSAPI provides both low-level and high level wrappers around the GSSAPI C libraries.
    While it focuses on the Kerberos mechanism, it should also be useable with other GSSAPI mechanisms.
  doc_url: https://pythongssapi.github.io/python-gssapi/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
