{% set name = "gssapi" %}
{% set version = "1.8.0" %}

package:
  name: python-gssapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f47ad4969f238e4e8edad0259965dc275f9a67d62cca7262aca946a7a81518e2
  patches:
    - 0001-fix-setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]
  script_env:
    - GSSAPI_SUPPORT_DETECT=false  # [build_platform != target_platform]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - krb5
    - pip
  run:
    - python
    - decorator

test:
  imports:
    - gssapi
    - gssapi.raw
    - gssapi.raw._enum_extensions

about:
  home: https://github.com/pythongssapi/python-gssapi
  license: ISC
  license_file: LICENSE.txt
  summary: A Python interface to RFC 2743/2744 (plus common extensions)
  doc_url: https://pythongssapi.github.io/python-gssapi/stable/
  dev_url: https://github.com/pythongssapi/python-gssapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
